spring.application.name=Gest_priere_springboot

server.port=${PORT:8080}
spring.datasource.url=jdbc:mariadb://76.13.121.48:3306/GestionPriere?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=ousmane
spring.datasource.password=ousmane
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS - autorise l'app mobile depuis n'importe ou
spring.web.cors.allowed-origins=*
